version: '3'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: exampledb
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  db_data:
    driver: local